using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.ComponentModel.Design.Serialization;
using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

namespace ResourcesClassGenerator
{
    internal class Program
    {
        static string masterPath;

        static void Main(string[] args)
        {
            masterPath = args[2];

            //System.Diagnostics.Debugger.Launch();
            string targetDirectory = args[1];

            string resourcesSourceFileLocation = args[0];

            string text = File.ReadAllText(resourcesSourceFileLocation);

            text = Regex.Replace(text, "#.*$", "", RegexOptions.Multiline);

            JObject root = JObject.Parse(text);

            StringBuilder sb = new StringBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"namespace {args[3]}.Generated.Paths;");
            sb.AppendLine($"public static class {args[4]}");
            sb.AppendLine($"{{");

            foreach (JProperty prop in root.Properties())
            {
                WriteClass(sb, prop.Name, (JObject)prop.Value, 1);
            }

            sb.AppendLine($"}}");

            string output = sb.ToString();

            File.Create(targetDirectory + "/ResourcePaths.g.cs").Close();
            File.WriteAllText(targetDirectory + "/ResourcePaths.g.cs", output);

        }

        static void WriteClass(StringBuilder sb, string className, JObject obj, int indentLevel)
        {
            string indent = new string(' ', indentLevel * 4);
            sb.AppendLine($"{indent}public static class {className}");
            sb.AppendLine($"{indent}{{");

            foreach (var prop in obj.Properties())
            {
                if (prop.Value.Type == JTokenType.Object)
                {
                    WriteClass(sb, prop.Name, (JObject)prop.Value, indentLevel + 1);
                }
                else if (prop.Value.Type == JTokenType.String && prop.Name.Contains("FileContent"))
                {

                    string fileText = File.ReadAllText(masterPath + (string)prop.Value!);
                    fileText = fileText.Replace("\n", "\\n");
                    fileText = fileText.Replace("\r", "\\r");

                    sb.AppendLine($"{indent}    public const string {prop.Name} = \"{fileText}\";");
                }
                else if (prop.Value.Type == JTokenType.String)
                {
                    sb.AppendLine($"{indent}    public const string {prop.Name} = \"{prop.Value.ToString()}\";");
                }
            }

            sb.AppendLine($"{indent}}}");
        }
    }
}
